<?php

return [
    'source_disk' => env('VIDEO_SOURCE_DISK', 'local'),
    'output_disk' => env('VIDEO_OUTPUT_DISK', 'public'),
    'disk' => env('VIDEO_OUTPUT_DISK', 'public'),
    'ffmpeg' => env('FFMPEG_BINARY', '/usr/bin/ffmpeg'),
    'ffprobe' => env('FFPROBE_BINARY', '/usr/bin/ffprobe'),
    'work_directory' => env('VIDEO_WORK_DIRECTORY', storage_path('app/video-processing')),
    'upload_directory' => 'product-video-uploads',
    'output_directory' => 'products/preview-videos',
    'chunk_size' => (int) env('VIDEO_CHUNK_SIZE', 10 * 1024 * 1024),
    'max_source_size' => (int) env('VIDEO_MAX_SOURCE_BYTES', 400_000_000),
    'max_source_bytes' => (int) env('VIDEO_MAX_SOURCE_BYTES', 400_000_000),
    'max_active_uploads' => (int) env('VIDEO_MAX_ACTIVE_UPLOADS', 3),
    'max_active_upload_bytes' => (int) env('VIDEO_MAX_ACTIVE_UPLOAD_BYTES', 800_000_000),
    'max_global_active_upload_bytes' => (int) env('VIDEO_MAX_GLOBAL_ACTIVE_UPLOAD_BYTES', 8_000_000_000),
    'minimum_free_bytes' => (int) env('VIDEO_MINIMUM_FREE_BYTES', 5_000_000_000),
    'max_duration_seconds' => (int) env('VIDEO_MAX_DURATION_SECONDS', 1_200),
    'max_landscape_width' => 1_920,
    'max_landscape_height' => 1_080,
    'max_portrait_width' => 1_080,
    'max_portrait_height' => 1_920,
    // Leave room for container overhead while guaranteeing a final file below 100 MB (decimal).
    'target_output_bytes' => min((int) env('VIDEO_TARGET_OUTPUT_BYTES', 90_000_000), 90_000_000),
    'max_output_bytes' => min((int) env('VIDEO_MAX_OUTPUT_BYTES', 100_000_000), 100_000_000),
    'audio_bitrate_kbps' => (int) env('VIDEO_AUDIO_BITRATE_KBPS', 96),
    'process_timeout' => (int) env('VIDEO_PROCESS_TIMEOUT', 7_000),
    'probe_max_output_bytes' => (int) env('VIDEO_PROBE_MAX_OUTPUT_BYTES', 131_072),
    'queue_connection' => env('VIDEO_QUEUE_CONNECTION', 'video_database'),
    'queue' => env('VIDEO_QUEUE', 'videos'),
    'upload_ttl_hours' => (int) env('VIDEO_UPLOAD_TTL_HOURS', 24),
    'assembly_stale_seconds' => (int) env('VIDEO_ASSEMBLY_STALE_SECONDS', 900),
    'assembly_lock_seconds' => (int) env('VIDEO_ASSEMBLY_LOCK_SECONDS', 900),
    'retention_days' => (int) env('VIDEO_RETENTION_DAYS', 7),
];
